language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
  - covr
  - devtools

r_github_packages:
  - codecov/example-r

jobs:
  include:
  - r: devel
  - os: osx
  - os: windows
  - r: release
  - r: 3.5
  - r: 3.4
  - r: 3.3

after_success:
  - Rscript -e 'library(covr);codecov()'
